services:
    postgres:
        container_name: postgres
        image: postgres
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - PGDATA=/data/postgres
        volumes:
            - postgres_data:/data/postgres
        ports:
            - 5432:5432
        env_file:
            - .env
        networks:
            - postgres-db-network

    pgadmin:
        container_name: pgadmin4
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
        volumes:
            - pgadmin_data:/var/lib/pgadmin
        ports:
            - ${PGADMIN_DEFAULT_PORT}:80
        env_file:
            - .env
        networks:
            - postgres-db-network

networks:
    postgres-db-network:
        driver: bridge

volumes:
    postgres_data:
    pgadmin_data: